version: '3'
services:
  app:
    build:
      context: converter
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app  
    container_name: converter_api_app
    networks:
      - web_net 
    ports:
      - "5000:5000"
    depends_on: 
      - db
  db: 
    container_name: cloud_conversion_db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud_conversion
    image: "postgres:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - ${PWD}/postgres-data:/var/lib/postgresql/data
  nginx:
    container_name: cloud_conversion_nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/
    depends_on:
      - app
networks:
  web_net:
      driver: bridge
volumes: 
  pg-data: 
    driver: local